In [1]:
import numpy as np
import matplotlib.pyplot as plt
import scipy, pandas
import librosa

In [2]:
print np.ones((5,2))

[[ 1.  1.]
 [ 1.  1.]
 [ 1.  1.]
 [ 1.  1.]
 [ 1.  1.]]


In [3]:
print scipy.randn(5)

[-1.96197402 -0.57141135  0.09142615  0.54855199 -1.47844704]


In [5]:
x = scipy.randn(5)
y = np.ones(5)
print x
print y
print np.dot(x, y)

[-0.53534461  0.16884029  0.79495902  2.35367023 -0.82741767]
[ 1.  1.  1.  1.  1.]
1.9547072639


In [6]:
x = np.arange(10)
y = np.ones(10)
print x < 5
print x < y

[ True  True  True  True  True False False False False False]
[ True False False False False False False False False False]


In [7]:
from scipy.spatial import distance

In [8]:
print distance.cosine([67, 0], [89, 0])
print distance.cosine([67, 0], [0, 89])

0.0
1.0


In [10]:
x = scipy.randn(5)
print x
x.sort()
print x

[-0.03774668  1.17013908 -1.11604913  1.32713218 -0.07644486]
[-1.11604913 -0.07644486 -0.03774668  1.17013908  1.32713218]


In [11]:
x = scipy.randn(3)
print x
ind = np.argsort(x)
print ind
print x[ind]

[-0.71859334  0.26801705 -0.69937183]
[0 2 1]
[-0.71859334 -0.69937183  0.26801705]
